data_dir: /mnt/hdd/jgammell/leakage_localization/downloads/dpav4
max_epochs: 10000
all_kwargs:
  classifiers_name: sca-cnn
  theta_lr: 1.0e-3
  gammap_lr: 1.0e-2
  identity_lambda: 1.0e-2
  calibrate_classifiers: false