data_dir: /mnt/hdd/jgammell/leakage_localization/downloads/one_truth_prevails
compute_ground_truth_assessments: true
compute_first_order_stats: true
run_supervised_hparam_sweep: false
train_supervised_model: false
compute_nn_attributions: false
pretrain_classifiers: false
run_ll_classifiers_hparam_sweep: true
run_leakage_localization: false
hparam_tune: false
max_classifiers_pretrain_steps: 1000
max_leakage_localization_steps: 4000
default_kwargs:
  classifiers_name: mlp-1d
  calibrate_classifiers: false
classifiers_pretrain_kwargs:
  theta_lr: 1.e-3
  budget: 1000.
  theta_lr_scheduler_name: CosineDecayLRSched
supervised_training_kwargs:
  classifier_name: mlp-1d
  lr: 1.e-4
  weight_decay: 1.e-2
  lr_scheduler_name: CosineDecayLRSched
leakage_localization_kwargs:
  theta_lr: 1.e-5
  etat_lr: 1.e-3
  etat_lr_scheduler_name: CosineDecayLRSched
  gradient_estimator: REBAR
  budget: 100.